version: "3.8"
services:
  app:
    build: .
    container_name: python-server
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 80:80
      - 5678:5678
    volumes:
      - ./app:/code/app
    # depends_on:
    #   - redis

  # redis:
  #   image: redis:alpine

  mongo:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin 
      MONGO_INITDB_ROOT_PASSWORD: LikeAndSubscribe
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
    driver: local 